# Generated by Django 3.1.4 on 2021-04-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
