# Generated by Django 3.1.4 on 2021-04-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210409_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='number',
            field=models.IntegerField(max_length=50),
        ),
    ]
