# Generated by Django 3.1.4 on 2021-04-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210409_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
