# Generated by Django 3.2.3 on 2021-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='title_butt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
