# Generated by Django 3.2.3 on 2021-07-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_career_title_butt'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='career',
            name='notice',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
