# Generated by Django 3.2.3 on 2021-07-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210724_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='career',
            name='title_tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
